[package]
name = "standalone_scraper"
version = "0.1.0"
authors = ["lew"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
zip = "0.5"
